polls/mypolls/urls.py
from django.urls import include,path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.PollListView.as_view(), name='poll-list'),
    path('polls/create', views.PollsCreateView.as_view(), name='poll-create'),
    path('polls/update/<slug:id>', views.PollsUpdateView.as_view(), name='poll-update'),
    path('polls/delete/<slug:id>', views.PollsDeleteView.as_view(), name='poll-delete'),
    path('choice/list/<slug:id>', views.ChoiceListView.as_view(), name='choice-list'),
    path('choice/create/<slug:id>', views.ChoiceCreateView.as_view(), name='choice-create'),
    path('choice/update/<slug:id>', views.ChoiceUpdateView.as_view(), name='choice-update'),
    path('choice/delete/<slug:id>', views.ChoiceDeleteView.as_view(), name='choice-delete'),
    # path('vote/update/<slug:id>', views.VoteUpdateView.as_view(), name='vote-update'),
    path('vote/update/<slug:id>', views.vote, name='vote-update'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mypolls.urls')),
]

polls/mypolls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/mypolls/forms.py
from django import forms
from .models import Question, Choice

class QuestionModelForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = [
            'question_text',
            'pub_date'
        ]
        widgets = {
            'pub_date': forms.DateTimeInput(format=("%d %b %Y %H:%M:%S %Z"),
                                             attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                    'type': 'date'}),
        }
class ChoiceModelForm(forms.ModelForm):
    class Meta:
        model =Choice
        fields = [
            'choice_text',
            'votes'
        ]

polls/mypolls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from .models import Question, Choice
from .forms import QuestionModelForm, ChoiceModelForm

# Create your views here.
class PollObjectMixin(object):
    model = Question
    lookup = 'id'

    def get_object(self):
        id = self.kwargs.get(self.lookup)
        obj = None
        if id is not None:
            obj = get_object_or_404(self.model, id=id)
        return obj

class ChoiceObjectMixin(object):
    model = Choice
    lookup = 'id'

    def get_object(self):
        id = self.kwargs.get(self.lookup)
        obj = None
        if id is not None:
            obj = get_object_or_404(self.model, id=id)
        return obj

class PollSearchMixin():
    model = None

    def get_queryset(self):
        queryset = self.model.objects.all()
        query = self.request.GET.get('search')

        if query:
            return queryset.filter(Q(question_text__icontains=query))

        return queryset

class PollListView(PollSearchMixin, ListView):
    template_name = 'mypolls/polls_list.html'
    paginate_by = 2
    model = Question


class PollsCreateView(CreateView):
    model =  Question
    form_class = QuestionModelForm
    template_name = 'mypolls/polls_create.html'
    success_url = reverse_lazy('polls:poll-list')

    def form_valid(self, form):
        return super().form_valid(form)


class PollsUpdateView(PollObjectMixin, UpdateView):
    model = Question
    form_class = QuestionModelForm
    template_name = 'mypolls/polls_create.html'
    success_url = reverse_lazy('polls:poll-list')


class PollsDeleteView(PollObjectMixin, DeleteView):
    model = Question
    form_class = QuestionModelForm
    template_name = 'mypolls/polls_delete.html'
    success_url = reverse_lazy('polls:poll-list')


class ChoiceListView(ListView):
    template_name = 'mypolls/choice_list.html'
    model = Choice
    paginate_by = 2

    def get_queryset(self):
        return Choice.objects.filter(question =self.kwargs.get('id'))

class ChoiceCreateView(ChoiceObjectMixin, CreateView):
    model =  Choice
    form_class = ChoiceModelForm
    template_name = 'mypolls/choice_create.html'
    success_url = reverse_lazy('polls:poll-list')


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.question = Question.objects.get(pk=self.kwargs.get('id'))
        self.object.save()
        return super().form_valid(form)

class ChoiceUpdateView(ChoiceObjectMixin, UpdateView):
    model = Choice
    form_class = ChoiceModelForm
    template_name = 'mypolls/choice_create.html'

    def get_success_url(self):
        data = Choice.objects.get(pk = self.object.pk)
        return reverse('polls:choice-list', args=(data.question.id,))

class ChoiceDeleteView(ChoiceObjectMixin, DeleteView):
    model = Choice
    form_class = ChoiceModelForm
    template_name = 'mypolls/choice_delete.html'

    def get_success_url(self):
        data = Choice.objects.get(pk=self.object.pk).question.id
        return reverse('polls:choice-list', args=(data,))


def vote(request, id):
    data = Choice.objects.get(pk=id)
    data.votes += 1
    data.save()

    return HttpResponseRedirect(reverse('polls:choice-list', args=(data.question.id,)))

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
</head>
<body>


{% block content %}{% endblock %}
</body>
</html>

polls/templates/mypolls/choice_create.html
{% extends 'base.html' %}

{% block content %}
<h3>{% if object %}Update{% else%}Create {% endif %}Choice </h3>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" name="submit">
</form>

{% endblock %}

polls/templates/mypolls/choice_delete.html
{% extends 'base.html' %}
{% block content %}
<form method = 'post'>
    {% csrf_token %}
    <p>Are you sure want to delete "<b>{{ object.choice_text}}</b>"?</p>
    <input type="submit" value="Delete">
</form>
{% endblock %}

polls/templates/mypolls/choice_list.html
{% extends 'base.html' %}
{% block content %}
<h3>Choice List</h3>

{% for object in object_list %}
<li>
    {{ object.choice_text }} - {{ object.votes }}
    <a href="{% url 'polls:choice-update' object.id %}">Update</a>
    <a href="{% url 'polls:choice-delete' object.id %}">Delete</a>
    <a href="{% url 'polls:vote-update' object.id %}">Vote</a>
</li>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

polls/templates/mypolls/polls_create.html
{% extends 'base.html' %}

{% block content %}
<h3>{% if object %}Update{% else%}Create {% endif %} Polls </h3>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" name="submit">
</form>

{% endblock %}

polls/templates/mypolls/polls_delete.html
{% extends 'base.html' %}
{% block content %}
<form method = 'post'>
    {% csrf_token %}
    <p>Are you sure want to delete "<b>{{ object.question_text}}</b>"?</p>
    <input type="submit" value="Delete">
</form>
{% endblock %}

polls/templates/mypolls/polls_list.html
{% extends 'base.html' %}

{% block content %}
{% load mypolls_extras %}
<h3>Polls List</h3>
<a href="{% url 'polls:poll-create' %}">Create New Poll</a>
<BR>
<form method="GET">
<label>Search</label>
<input name="search" id="search" type="text">
<button type="submit">Submit</button>
</form>
{% for data in object_list %}
<ul>
    <li>{{data.question_text}}</li>
    <a href="{% url 'polls:choice-create' data.id %}">Add Choice</a>
    <a href="{% url 'polls:choice-list' data.id %}">Choice List</a>
    <a href="{% url 'polls:poll-update' data.id %}">Edit</a>
    <a href="{% url 'polls:poll-delete' data.id %}">Delete</a>
</ul>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="{% my_url 1 'page' request.GET.urlencode %}">&laquo; first</a>
            <a href="{% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">next</a>
            <a href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}